server:
  port: 8080

spring:
  banner:
    image:
      pixelmode: block
      width: 256
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  global-config:
    banner: off

